[build]
publish = "public"
command = "git submodule update --init --recursive && npm run build"

[context.production.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build"

[context.split1.environment]
HUGO_VERSION = "0.145.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build"

[context.deploy-preview.environment]
HUGO_VERSION = "0.145.0"

[context.branch-deploy]
command = "npm run build"

[context.branch-deploy.environment]
HUGO_VERSION = "0.145.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# --- Cloudinary Build Plugin ---
[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    # You already set CLOUDINARY_CLOUD_NAME / API KEY / SECRET in Netlify UI.
    # You can also set cloudName here, but it's optional if the env var exists.
    # cloudName = "your-cloud-name"

    # Where your site SERVES images from (URL paths), not filesystem folders.
    # Hugo's /static/img -> served at /img, /static/images -> /images, etc.
    imagesPath = ["/img", "/images", "/assets/img", "/assets/images"]

    # Where to store in Cloudinary (organizes your library)
    folder = "site/production"

    # Optional: cap delivered size without changing DOM dimensions.
    # This mimics "limit to 1600px wide" behavior.
    [plugins.inputs.maxSize]
      width = 1000
      # height = 0     # omit to preserve aspect ratio
      # dpr = "1.0"    # optionally "2.0" for high-DPR displays
